services:
  work-order-php:
    build: .
    container_name: work-order-php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  work-order-nginx:
    image: nginx:alpine
    container_name: work-order-nginx
    ports:
      - "8085:80"   # boleh sementara debug, nanti bisa dihapus
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/sites-available/pralon.conf
    depends_on:
      - work-order-php
    networks:
      - laravel

networks:
  laravel:
